version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: raghu
      MYSQL_DB: nodejs_db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: raghu
      MYSQL_DATABASE: nodejs_db
    ports:
      - "3306:3306"
